accounts:
  - name: alice
    coins: ["200000000bls"]
  - name: bob
    coins: ["100000000bls"]
validator:
  name: alice
  staked: "100000000bls"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000bls"]
genesis:
  chain_id: "bls-edgenet-1"
  app_state:
    staking:
      params:
        bond_denom: "bls"
    mint:
      params:
        mint_denom: "bls"
build:
  binary: blsd
