accounts:
  - name: alice
    coins: ["200000000ubls"]
  - name: bob
    coins: ["100000000ubls"]
validator:
  name: alice
  staked: "100000000ubls"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000ubls"]
genesis:
  chain_id: "bls-edgenet-1"
  app_state:
    bank:
      denom_metadata:
        - description: Blockless Network Token
          name: BLS
          base: ubls
          symbol: bls
          display: bls
          denom_units:
            - denom: ubls
              exponent: 0
            - denom: bls
              exponent: 6
    staking:
      params:
        bond_denom: "ubls"
    mint:
      params:
        mint_denom: "ubls"
build:
  binary: blsd
